project:
  type: website

website:
  site-url: https://clabornd.github.io/dmcblog
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/clabornd
      - icon: twitter
        href: https://twitter.com/
format:
  html:
    theme: cosmo
    css: styles.css

jupyter: base
