project:
  type: website

website:
  site-url: https://clabornd.github.io/dmcblog
  twitter-card: true
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/clabornd
      - icon: linkedin
        href: https://www.linkedin.com/in/dmclaborne/
    left:
      - text: "Home"
        file: index.qmd
format:
  html:
    theme: cosmo
    css: styles.css

jupyter: dmcblog