[project]
name = "dmcblog"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.4",
    "matplotlib-inline>=0.1.7",
    "numpy>=2.0.2",
    "pandas>=2.3.1",
    "seaborn>=0.13.2",
    "torch>=2.7.1",
    "transformers>=4.53.2",
]
