on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    branches: [master]
    paths-ignore:
      - README.md
      - .gitignore

name: Deploy blog

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - uses: actions/setup-python@v4
      - run: uv sync

      - name: Render Quarto
        uses: quarto-dev/quarto-actions/render@v2
        if: github.event_name == 'pull_request' && github.base_ref == 'master'
        env:
          QUARTO_PYTHON: .venv/bin/python

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'